### ISSUE TITLE
why aren't the PTModel topic distributions equal for documents of the same pseudodocument?

### ISSUE THREAD

**Issue by RutgerEttes** [bab2min/tomotopy#119]
When working with the PTModel, i noticed that the topic distributions obtained via doc.get_topic_dist() would return different distributions for documents that had been assigned to the same pseudodocument. If i read the original paper correctly, the topic distributions for each document should be the same as the topic distribution for the pseudodocument it is part of. Is this a bug or am I missing something?

**Comment by bab2min** [comment]
Hi @RutgerEttes ,
Thank you for asking a good question.
As you said, currently `doc.get_topic_dist()` of `PTModel` return the distribution based on topic allocation for the real document's words, so it may be different from the pseudo document's one. 
I'll add an optional argument `from_pseudo_doc` to `get_topic_dist()` in the next update so that we can choose whether to get the distribution from a pseudo document or a real document.
