### ISSUE TITLE
[QUESTION] Is there a way to remove stop words?

### ISSUE THREAD

**Issue by batmanscode** [bab2min/tomotopy#130]
I'm not sure if I've missed it in the docs but is there a way to remove stop words from a pre-defined list?

Right now I'm using `rm_top` for this.

**Comment by bab2min** [comment]
Hi~ @batmanscode ,
Currently models including `tomotopy.LDAModel` and its derived classes do not provide such functionality.
If you can use `tomotopy.utils.Corpus` you can set your stopword to its `__init__` method, otherwise you should filter stopwords manually.

I'll think about a good interface to specify stopwords when inserting corpus into topic model or creating corpus.

**Comment by batmanscode** [comment]
I see, thank you @bab2min!

And idea for the interface:

Two new arguments:
* `stopwords` with parameters `None`, `"default"` and `"custom"`
* and `stopwords_list` with `"default"` and `[user specified path]`

where `stopwords = "default"` uses a built-in list of common stopwords and `"custom"` requires adding a path to a custom list by using `stopwords_list = [path]`
