### ISSUE TITLE
Loading a fairly large model takes a long time

### ISSUE THREAD

**Issue by erip** [bab2min/tomotopy#180]
I have a 6.5GB model trained on 10M docs to model 100 topics trained the usual way. I'm trying to load the model and I'm finding that load times are incredibly high. For reference, I've been monitoring `top` and my program has only loaded ~5.1GB of the 6.5GB model after 10 minutes.

I suspect this is because I used default `save` with `full=True`... Should I expect a model with `full=False` to load faster?

**Comment by bab2min** [comment]
Hi @erip 
Yes, the model saved with `full=True` argument has all parameters related to whole train, thus it may take a long time to re-load it. If you save the model with `full=False`, you cannot continue to train with this model, but you can load faster.

**Comment by erip** [comment]
Thanks very much, @bab2min! It seems like if the model is binarized it shouldn't take long to reload. I haven't looked at the details so sorry for the silly question, but does the model use numpy binarization under the hood? If so, it could be quick to deserialize even if full (though maybe I don't appreciate the complexity here).

**Comment by bab2min** [comment]
@erip Actually, the package doesn't use numpy binarization for loading & saving, but uses a custom serialization functions.
And it is true that there are many features related to backward compatibility in the custom functions, so their process is somewhat inefficiently.
I'll check if it can be improved or re-implement the loading & saving in the near future.

**Comment by bab2min** [comment]
I finally discovered the bottleneck in `LDAModel.save`, `LDAModel.load`. Due to data discontinuity, the process of reading and writing data fields in the serializer was being called separately into multiple system calls. To improve this, I performed optimization to make memory contiguous and integrate multiple system calls into one. Below is the benchmark code and result.

```python
# Simple Benchmark Code
import time

import numpy as np
import tomotopy as tp

np.random.seed(0)
docs = []
for n in np.random.randint(50, 151, size=10000):
    docs.append(list(map(str, np.random.randint(10, size=n))))

mdl = tp.LDAModel(k=20)
for doc in docs:
    mdl.add_doc(doc)

mdl.train(0)
times = []
for _ in range(30):
    start = time.perf_counter()
    mdl.save('test.model.bin')
    times.append(time.perf_counter() - start)
times = np.array(times)
print(f'Saving LDA: {times.mean()*1000:.2f} +- {times.std()*1000:.2f}ms')

times = []
for _ in range(30):
    start = time.perf_counter()
    mdl = tp.LDAModel.load('test.model.bin')
    times.append(time.perf_counter() - start)
times = np.array(times)
print(f'Loading LDA: {times.mean()*1000:.2f} +- {times.std()*1000:.2f}ms')

mdl = tp.GDMRModel(k=20, degrees=[3, 2])
for doc in docs:
    mdl.add_doc(doc, numeric_metadata=[0, 0], metadata='meta')

mdl.train(0)
times = []
for _ in range(30):
    start = time.perf_counter()
    mdl.save('test.model.bin')
    times.append(time.perf_counter() - start)
times = np.array(times)
print(f'Saving GDMR: {times.mean()*1000:.2f} +- {times.std()*1000:.2f}ms')

times = []
for _ in range(30):
    start = time.perf_counter()
    mdl = tp.GDMRModel.load('test.model.bin')
    times.append(time.perf_counter() - start)
times = np.array(times)
print(f'Loading GDMR: {times.mean()*1000:.2f} +- {times.std()*1000:.2f}ms')
```

<table>
<tr><th></th><th>Saving LDA</th><th>Loading LDA</th><th>Saving GDMR</th><th>Loading GDMR</th></tr>
<tr><th>Windows (x64), Python3.12, tomotopy==0.12.7</th>
<td>1101.25 +- 11.53ms</td><td>879.67 +- 4.12ms</td><td>1595.20 +- 21.29ms</td><td>1092.06 +- 9.76ms</td></tr>
<tr><th>Windows (x64), Python3.12, tomotopy==0.13.0</th>
<td>93.08 +- 4.01ms</td><td>71.36 +- 3.79ms</td><td>123.08 +- 3.73ms</td><td>101.46 +- 5.18ms</td></tr>
</table>

As a result, I were able to confirm a speed improvement of more than 10 times in both `save` and `load`, which will be applied in the next update.
