### ISSUE TITLE
add num_timepoints & num_docs_by_timepoint for DTModel

### ISSUE THREAD

**Issue by bab2min** [bab2min/tomotopy#59]
The current `tomotopy.DTModel`  is missing some features about the number of timepoints and documents. Suggest adding following properties into `DTModel`.
* `num_timepoints` (or `t`) : the value that is input as `t` of `__init__`
* `num_docs_by_timepoint` : the number of documents belonging to each timepoint

**Comment by ebergam** [comment]
Hi @bab2min , thanks a lot for this great work! 

Are you planning to implement these features soon? It is quite crucial to be able to use the num_docs_by_timepoints parameter in order to be able to use your library.

This is another interesting resource you might be interested in https://github.com/GSukr/dtmvisual

thanks a lot!

**Comment by bab2min** [comment]
Hello @ebergam, thanks for your attention to my work!
Currently I'm implementing the next version of tomotopy, and it will include this enhancement. So please wait a few more days.

**Comment by ebergam** [comment]
Great, looking forward! 
Thank you @bab2min :)
