### ISSUE TITLE
Calling `infer` causes a crash

### ISSUE THREAD

**Issue by RUMCS** [bab2min/tomotopy#62]
Hi I need to extract the documents per inferred topic using HDP, how can I do this? Thank you.

**Comment by bab2min** [comment]
Hello @RUMCS, sorry for late feedback.
What you want is to pick documents based on its topic, isn't it?
Since, in topic models including HDP, every document contains many topics, it is ambiguous to decide which document is on a particular topic.
Let's briefly define 'relatedness' to certain topics of a document as follows:
- A document is related to topic X if topic X is in the top 'n' among the distribution of topics in the document.

In this case, the documents related to each topic can be extracted with following codes.

```
# we use only top-1 topic for relatedness
top_n = 1

# initialize model with appropriate parameters
mdl = tp.HDPModel()

#
# ... add_doc and training ...
#

# prepare documents for inference
docs = []
for line in open('some_docs.txt'):
  docs.append(mdl.make_doc(line.strip().split()))

# let's infer
dist, ll = mdl.infer(docs)

# extract documents related to each topic
docs_per_topic = [[] for _ in range(mdl.k)]
for doc in docs:
  for topic, weight in doc.get_topics(top_n=top_n):
    docs_per_topic[topic].append(doc)

# print documents related to each topic
for k in range(mdl.k):
  if not mdl.is_live_topic(k): continue
  print('Topic #{} {}'.format(k, ' '.join(word for word, _ in mdl.get_topic_words(top_n=5))))
  for doc in docs_per_topic[k]:
    print(doc)
  print()
```

You can control the extracted documents by chaning top_n value or adding another condition such as weight threshold of topics.

**Comment by bab2min** [comment]
@fuaduae Oops, sorry for late answer.
The code in the above comment has typo errors.

`mdl.get_topic_words(top_n=5)` should be corrected to `mdl.get_topic_words(k, top_n=5)`.

```
for k in range(mdl.k):
  if not mdl.is_live_topic(k): continue
  print('Topic #{} {}'.format(k, ' '.join(word for word, _ in mdl.get_topic_words(k, top_n=5))))
  for doc in docs_per_topic[k]:
    print(doc)
  print()
```

**Comment by Jurgita-DS** [comment]
I am trying to get topic probabilities for each document after training an HDP model but the kernel keeps dying. I only have 12,000 documents and I tried scoring in 100 document chunks but still the same issue. I tried changing together parameter to False but it didn't make any difference either. 
I was able to generate topic probabilities on the same set of documents with no issues using  LDA model.

`
for i in range(0, len(texts), 100):
    doc_inst = [model.make_doc(text) for text in texts[i:i+100]]
    review_topics = model.infer(doc_inst, together = True)
` 
Any suggestions?

**Comment by bab2min** [comment]
Hi @Jurgita-DS,
Could you share the version of your python and tomotopy where the problem occurs?

**Comment by Jurgita-DS** [comment]
Hi @bab2min,
I am using python version 3.7.4 and tomotopy  0.10.2.

The issue seems to be somehow related with scoring certain document instances, however, I cannot see anything wrong with those documents.
texts is a list of documents where each document is a list of tokens, e.g. [[word1, word2], [word3, word4, word5]].
If I, for example, exclude the 8000th document the below code works fine.

```
doc_inst = [model.make_doc(text) for text in texts[8001:8500]]
doc_topics = model.infer(doc_inst, together = True)
```
Also if I only include the 8000th document the code runs with no issue.

```
doc_inst = [model.make_doc(text) for text in texts[8000]]
doc_topics = model.infer(doc_inst, together = True)
```

However, neither of the below two options work. Both cause the kernel to die.

```
# Generate topics for documents 8000 and 8001st
doc_inst = [model.make_doc(text) for text in texts[8000:8002]]
doc_topics = model.infer(doc_inst, together = True)

# Generate topics for document 8000th
doc_inst = [model.make_doc(text) for text in texts[8000:8001]]
doc_topics = model.infer(doc_inst, together = True)
```
I cannot see anything wrong with the document 8000. It contains a small number of words which all look fine to me.

I have also tried converting the HDP model into LDA, however, got the below error.
'there is a document with uid =  already'
This is the code I used:
`model_conv = model.convert_to_lda(topic_threshold = 0)`

I am not sure if it is related with the first issue of kernel dying or it's a separate one.
I have checked that there are no empty documents in the corpus (all contain at least one token), and no strange tokens (e.g. space).

I hope this helps. 
I am working with the data that I cannot be shared publicly so I am not able to share the data and the model that is causing the issue. I tried running the same code on the open source data but wasn't able to reproduce the error.

**Comment by bab2min** [comment]
@Jurgita-DS
Thank you for sharing details.
It seems that the combination of the 8000th document's content and the trained HDPModel cause a crash.
Probably there is a potential flaw in the code on the current `infer` method of HDPModel. As a result of writing the test code as follows in the same environment as the one you shared with, we found that a crash occurs in the infer function with some probability.

Based on your situation , I wrote the following test code.
When I ran it in the same environment that you shared with me, I confirmed that a crash occurs in the infer method sometimes.
```
while 1:
  import tomotopy as tp
  mdl = tp.HDPModel(min_cf=2)
  mdl.add_doc("a b c d e f".split())
  mdl.add_doc("1 2 3 d e f".split())
  mdl.add_doc("c d".split())
  mdl.add_doc("3 f".split())
  
  mdl.train(1000)
  
  doc1 = mdl.make_doc("a b c".split())
  doc2 = mdl.make_doc("b c d e".split())
  
  mdl.infer([doc1, doc2])
```

Also, the problem where `convert_to_lda` raises `there is a document with uid = already` exception seems another bug. 

I will try to determine the cause of two bugs you reported and fix them.
Thank you for your reporting again!

**Comment by bab2min** [comment]
@Jurgita-DS 
I've fixed code that is suspected to be causing the problem. After removing current tomotopy package, you can install dev version using following command:
```
pip install --index-url https://test.pypi.org/simple/ tomotopy
```
I would appreciate it if you try to do the same code with the dev version.

**Comment by Jurgita-DS** [comment]
@bab2min 
I have tested the dev version and `model.infer()` worked fine, generated topic probabilities for all 12k documents.
However, `convert_to_lda`  is causing the kernel to die.

**Comment by bab2min** [comment]
@Jurgita-DS 
Uhmmm, could you share the value for docs' `uid` of `Corpus` feeded to `HDPModel` if you provided `uid` for docs?

**Comment by Jurgita-DS** [comment]
@bab2min 
How do I get uid of ```Corpus```?
This is how I created corpus:
```
corpus = tp.utils.Corpus()
for doc in texts:
    corpus.add_doc(words = doc)
```

**Comment by bab2min** [comment]
@Jurgita-DS 
Aha, you created without `uid` param. I'll check it. Thank you!

**Comment by giuliaok** [comment]
Hi, I am using Python 3.8 and Tomotopy 0.11.1, having a similar issue as @Jurgita-DS . I tried to downgrade to tomotopy==0.10.2 and the problem reproduces equally. 

While working both on Jupyter various methods would kill my kernel - `get_topic_dist` and `get_topics` - in particular. As Jupyter wouldn't provide me with loads of debugging information I run my script from the terminal where I got a segmentation fault. This is not a data dimension issues, as this happen also when i am trying these methods on 1 single document created with `make_doc`. The `infer` method seems to work in small samples. 

Any news on this? Thank you!

**Comment by bab2min** [comment]
Hi @giuliaok ,
Sorry for providing the unstable version.
Could you share your code that caused a segmentation fault? 
I cannot reproduce similar problems in my setting, thus I have a difficulty to figure out that bug.
If you have code or data that cannot provide publicly, it is okay to send them to my personal email (bab2min@gmail.com). I'll use them for only debugging, not any other purpose and delete them after finding the cause.

**Comment by giuliaok** [comment]
Hi, thank you for coming back and no apologies needed, I love the package! 
I have issues in reproducing the problem myself. If I have a model, let's say: 

```

mdl = tp.HDPModel(tw = tp.TermWeight.IDF, min_cf = 30, rm_top = 20, gamma = 0.8, alpha = 0.1, initial_k = 12, seed = 99999)

```

and add documents to it with: 

```
for vec in documents:
    mdl.add_doc(vec)
```

where documents is whichever type of text list, I then train the model as:

```
mdl.burn_in = 1000
mcmc_iter = 5000
for i in range(0, mcmc_iter, 100):
    mdl.train(100, workers = 3)
  
```

Until here everything works perfectly. When I try to apply whichever method to the trained model, such as for instance `mdl.summary()` the kernel randomly dies due to a segmentation fault. What is even more mysterious to me is that this does not happen all the times but completely at random: for instance, at the moment I have two Jupyter Notebooks opened on the same virtual environment (so same dependencies, same python version etc.) - on one notebook I am able to use all methods, on the other I get a segmentation fault as soon as I try to use any method. I am working on MacOS Catalina. 

I understand this sounds very weird but I swear this is what is happening 😂

Thanks!

**Comment by bab2min** [comment]
@giuliaok 
Thank you for sharing your detail. I'll examine it.

**Comment by bab2min** [comment]
@giuliaok, could you do me a favor? 
Can you check if the kernel randomly dies in your environment when running the same code but without argument `min_cf = 30, rm_top = 20` ?

**Comment by bab2min** [comment]
@giuliaok 
Honestly, I haven't yet figured out the obvious cause of the problem.
But, I found a bug where words excluded by `min_cf` or `min_df` were given an inappropriate topic id and it may cause a crash at showing topic information of those words. 
I've updated a new test version. I'd appreciate it if you can run the same with the new version  to see if the problem occurs.

```console
$ pip install -U --index-url https://test.pypi.org/simple/ tomotopy==0.12.0 # install a test version
```

**Comment by julienOlivier3** [comment]
@bab2min 
I can confirm the kernel dies regardless of whether you specify `min_cf`, `rm_top` or `min_df`. To me it happens when working with a PLDAModel which I train on a corpus of ~6,000 documents with each document having at most a character length of 1,000,000. After training the model sucessfully infering the topic distribution of a new document via make_doc() and get_topic_distribution() causes the kernel to die. Strangely enough, and similar to the problem of @Jurgita-DS, the kernel only dies if I infer topic distributions of a list of documents. If I infer the topic distribution of the documents individually (i.e. not via a list comprehension or a loop), everything seems to work fine.

My first hunch is that the problem might be a storage related issue. The trained PLDAModel is quite large (~900 MB) and the list of documents for which I want to infer topic distributions is around 600 MB.

Although I cannot share my data, I am happy to assist in solving the issue. I think your package is a great contibution! So do let me know if you need additional info.

Best 
Julian

**Comment by bab2min** [comment]
Hi @julienOlivier3 
Thank you for sharing your experience.
Can you test if the crash still occurs when you provide a small list of docs (2 or 3)?
In my opinion, if it's a storage issue, it shouldn't happen when a short list is given, but only when a long list is given.
Otherwise, there may be some bugs in implementation of infer for multiple docs.

**Comment by bab2min** [comment]
@mmawada 
Yes, I checked the mail. 
I tried to reproduce them but failed. It seems to be a problem that is probably only happening with certain data. Could you share your code piece and data? 
If it is difficult for you to share your code or data publicly, it is okay to send them to my email.

**Comment by mmawada** [comment]
The data files are over 600MB , where can I share them with you privately
?

**Comment by mmawada** [comment]
I attach the data files below and the code .
 hdp_model_eqwgts.bin
<https://drive.google.com/file/d/1rRX0alChLrjCoTIzD9G_472I68xZ2pJv/view?usp=drive_web>
 hdp_model_pmi.bin
<https://drive.google.com/file/d/1JOPdsi4Lh-o3II-Kfu5tc34hUJsVVIDE/view?usp=drive_web>
With the same data the convert_to_lda was working with version 10 , but
with the new version 12 , the kernel is dying so it is definitely a code
bug , memory issues etc.
here are the
the codes are :
hdp_eqwgts = tp.HDPModel.load("models/hdp_model_eqwgts.bin")
hdp_pmi = tp.HDPModel.load("models/hdp_model_pmi.bin")
hdp_idf = tp.HDPModel.load("models/hdp_model_idf.bin")
hdp_idf3 = tp.HDPModel.load("models/hdp_model_idf3.bin")

You can load any of the above hdp and will crash the kernel .  for example
you can try :

# use the best IDF model for HDP
ldaimplied_idf, new_topic_id =
hdp_idf3.convert_to_lda(topic_threshold=0.015)

or

# use the best model given by coherence test which is of HDP PMI save from
the bin
ldaimplied_pmi, new_topic_id = hdp_pmi.convert_to_lda(topic_threshold=0.015)

Look forward to hearing from you.
Thank you,
Mark

**Comment by bab2min** [comment]
Thanks @mmawada 
I've received the file you shared well. I'll examine that bug!

**Comment by bab2min** [comment]
@mmawada 
It was confirmed that the cause of the problem was that the words removed from the modeling by `min_cf`, `min_df` or `rm_top` were not properly processed in the converting to the LDA model.
The problem can be reproduced when calling `convert_to_lda` of HDP model with `min_cf > 0`, `min_df > 0` or `rm_top > 0`.

This bug will be patched in the next update. Thank you for reporting the bug again!

**Comment by mmawada** [comment]
I am very glad you found the bug . Could you send me the updated file as
soon as possible, please?  I would I appreciate it if you email it to me
too .

Thank you very much,
Mark

**Comment by MarkWClements** [comment]
> @Jurgita-DS
> Aha, you created without `uid` param. I'll check it. Thank you!

I am having an issue when training an LDA model, I get 'uid' values of  `''` for all documents. I also don't see any option to provide document ids to the Corpus as you mention here. Is there the capability of including user defined document ids?

**Comment by mmawada** [comment]
@bab2min , I presume  Dev 0.12.2 the version  has the correction to the bug I found above .  How can we upload this to update the installed version of tomotopy ?  Thank you

**Comment by bab2min** [comment]
@mmawada 
Now a test binary for v0.12.2 is building. After building, you can get it using following command:

```console
$ pip install -U --index-url https://test.pypi.org/simple/ tomotopy==0.12.2
```

**Comment by mmawada** [comment]
Thanks a lot! Please let me know when the building is done.

**Comment by bab2min** [comment]
@mmawada Done! (https://github.com/bab2min/tomotopy/actions/runs/1192523849)

**Comment by mmawada** [comment]
Awesome, thanks!
